devshared: &devshared
  adapter: mysql2
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8
  reconnect: true
  pool: 5

development:
  <<: *devshared
  database: sidenotes_development

test: &test
  <<: *devshared
  database: sidenotes_test
